spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: '@Data-Box1'
  jpa:
    hibernate:
      ddl-auto:  update #create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#    &allowPublicKeyRetrieval=true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  #        include: "health, beans, metrics"
  #        exclude: "caches"
  #    base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always

dummyService:
#  address: 0.0.0.0
  address: 127.0.0.1
  port: 8080

#server:
#  port : 8082

#logging:
#  level:
#    com.restapi.rest_demo: DEBUG
