spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=true&requireSSL=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE


hikari:
  maximum-pool-size: 10

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info


server:
  port: 5000